### ISSUE TITLE
timeout after quick restarts

### ISSUE THREAD

**Issue by Juice2019** [JonasPed/homeassistant-eloverblik#11] opened 2020-04-22 22:04 UTC
Hey Jonas

First off thanks for integration. There is no doubt this will become a hit in the danish hass community..

I recived a timeout today from the service after doing 2 restarts within 10 minutes..
`Exception: <class 'requests.exceptions.ReadTimeout'>`

Maybe a workaround is possible, as this makes it impossible to pull data after the timeout?

**Comment by briis** [comment] 2020-04-23 09:01
I get the same, just after 1 restart and all sensors keep being unavailable.

**Comment by JonasPed** [comment] 2020-04-23 19:11
There is not really any workaround as the eloverblik.dk api is rather unstable and at times also very slow. If you get an timeout it will try to pull data again after one hour.

**Comment by briis** [comment] 2020-04-24 05:50
I can confirm that the sensors came back after an hour or so without me doing anything.

**Comment by JonasPed** [comment] 2020-05-04 19:31
Closing the issue because it is really not something I can do anything about.

**Closed by JonasPed** 2020-05-04 19:31 UTC
